name: 'Download files from PR'
description: 'Download modified files from specific Pull Request'
inputs:
  token:
    description: 'The GitHub token to use for making API requests'
    required: true
  owner:
    description: 'The owner of the GitHub repository you want to download files'
  repo:
    description: 'The name of the GitHub repository you want to download files'
  ref:
    description: 'The Git ref of the commit you want to download files'
  prNumber:
    description: 'The Pull Request number you want do download files'
    required: true
  filterPath:
    description: 'Filter files to be downloaded by path'
  validate:
    description: 'Check to validate Content Objects consistency'
    required: true
    default: false
  environment:
    description: 'Validates educational object on selected environment'
    required: true
    default: 'staging'
outputs:
  encodedRemovedFilenames:
    description: 'Encoded Base64 string that contains the name of the removed files'
runs:
  using: 'node12'
  main: 'dist/index.js'
