name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        token: 'my-token'
        owner: 'my-org'
        repo: 'my-repo'
        ref: 'b83924d03941d253d388e688fdad178f8f727112'
        prNumber: '34'
        storagePath: 'tmp/my'
        filterPath: 'content'
